EXPERIMENT_PARAMS:
  drugs: 'Pembro'
  tissues: ['STAD']
  rng_seed: 12345
  alpha: 0.5
  do_hops: True
  num_hops: 1
  fdrThresh: 0.002
  minTPM: 0.0
  num_iters: 20
  probThresh: 0.9
  subsamplePct: 0.75
  experiment_type: 'strict'

DIRECTORIES:
  data_dir: "../data/expression"
  geneset_dir: "../data/genesets/"
  network_dir: "../data/networks/"
  result_dir: "../results/"

NETWORK_PARAMS:
  topology: 'tight'
  weighting: 'unweighted'

CURVATURE_PARAMS:
  path_method: "all_pairs"
  min_degree_base: 1
  min_degree_exp: -5 
  min_distance_base: 1
  min_distance_exp: -5
  sinkhorn_thresh: 20000
  epsilon: 1.0

FEATURE_PARAMS:
  pvalue_thresh: 0.05
  lcc_only: False

OT_PARAMS:
  sinkhorn: False
  regParam: 0.01

MODEL_PARAMS:
  model_name: "LogisticRegression"
  min_C: 0.1
  max_C: 2
  C_step: 0.3
  max_iter: 10000


FIELD_NAMES:
  weight_field: "weight"
  rename_field: "gene"
  density_field: "density"
  edge_curvature_field: "ricci_curvature"
  node_curvature_field: "node_curvature"
  norm_node_curvature_field: "norm_node_curvature"
