EXPERIMENT_PARAMS:
  drug: 'erlotinib'
  sources: ['BRCA']
  targets: ['LUAD']
  rng_seed: 12345
  n_iters: 20
  exp_types: ['strict']
 
DIRECTORIES:
  data_dir: "../data/expression"
  geneset_dir: "../data/genesets/"
  network_dir: "../data/networks/"
  result_dir: "../results/"


FEATURE_PARAMS:
  edge_pv_threshs: [0.1,0.05]
  node_pv_threshs: [0.1,0.05]
  norm_node_pv_threshs: [0.1,0.05]


MODEL_PARAMS:
  model_name: "LogisticRegression"
  min_C: 0.1
  max_C: 1
  C_step: 0.05
  max_iter: 1000